x = input('Digite algo):')
print('o tipo é', type(x))
print('É alphanumerico?', x.isalnum())
print('É alphabetico?', x.isalpha())
print('É numerico?', x.isnumeric())
print('É um decimal?', x.isdecimal())
print('É um digito?', x.isdigit())
print('É somente espaços?', x.isspace())
print('Está em maiusculas?', x.isupper())
print('Está em minusculas?', x.islower())
print('Está capitalizada?', x.istitle()
      )