print('Opa eai meu funcionário do mês, vamo conversar.')
sl = float(input('O seu salário atual é de quanto mesmo?'))
au = float(sl*0.15)
sl2 = float(sl+au)
print(f'Perfeito, como você é um ótimo funcionario, até o proximo bimestre, seu salário ira de RS{sl}, para R${sl2:.6} com um aumento de 15%!')
