print('Bem vindo ao cadastro de herói')

nome = input('Qual o seu nome?')
ego = input('Qual o nome do seu Alter-Ego?')
print('Lista de Ranks')
print('S')
print('A')
print('B')
print('C')
rank = input('Qual o seu rank de herói?')
comida = input('O que você mais gosta de comer?')
print('Lista de Classes')
print('Mage')
print('Ranged')
print('Melee')
print('Summoner')
classe = input('Qual sua classe?')
print('Pois bem senhor(a){0}' .format(nome))
print('Aqui está seu cadastro')
print('Codinome: {0}'.format(ego))
print('Rank: {0}' .format(rank))
print('Prato predileto: {0}' .format(comida))
print('Classe: {0}' .format(classe))