print('Bem vindo ao cadastro de herói')

nome = input('Qual o seu nome?')
ego = input('Qual o nome do seu Alter-Ego?')
ranks = ['S', 'A', 'B', 'C']
print('Lista de Ranks')
print('S')
print('A')
print('B')
print('C')
rank = input('Qual o seu rank de herói?')
comida = input('O que você mais gosta de comer?')
print('Lista de Classes')
print('Mage')
print('Ranged')
print('Melee')
print('Summoner')
classe = input('Qual sua classe?')
print(f'Pois bem senhor(a){nome}')
print('Aqui está seu cadastro')
print(f'Codinome: {ego}')
print(f'Rank: {rank}')
print(f'Prato predileto: {comida}')
print(f'Classe: {classe}')